version: '3.8'

services:
  front:
    build:
      context: . # Usa o Dockerfile que está na raiz
    working_dir: /app
    command: ['npm', 'run', 'build']
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tunnel

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html
    depends_on:
      - front
    networks:
      - tunnel

networks:
  tunnel:
    external: true
